### ISSUE TITLE
Show members publicly?

### ISSUE THREAD

**Issue by maurolepore** [nmnh-r-users/meetups#2]
Our names as members of the nmnh-r-users organization (https://github.com/nmnh-r-users/) are private. Here is a good reason to make them public.

The R community values this kind of meetup but we can't get credit unless we make our work and names public. For example, to apply to [rstudio::conf(2019) diversity scholarships](https://blog.rstudio.com/2018/08/10/rstudio-conf-2019-diversity-scholarships/) applicants need to show they are active members of the R community.

**Comment by maurolepore** [comment]
Thanks for fixing this! I accepted your invitation and made my name public. 

![image](https://user-images.githubusercontent.com/5856545/44163069-477e6280-a090-11e8-9794-3e0ef981b110.png)

**Comment by megbalk** [comment]
That's a great idea! Next week?

**Comment by maurolepore** [comment]
Did you mean next week: Wed 22?, or next meetup on schedule: Wed 29?
I can either day.

**Comment by megbalk** [comment]
I meant Aug. 29th, sorry!

**Comment by maurolepore** [comment]
Great! We can keep the discussion about that meetup at #3.
